# Broadcast Messages                                                                                 

broadcasts:
  - "rosePOP GET RAFFLE TICKET IN POINTS STORE FOR A rosePOP  rosePOP CHANCE TO GET DRAWN IN GIF FORM rosePOP"
  - "rosClap FORM TO GET INTERVIEWED https://bit.ly/38hT7Dy rosClap"
  - "rosD https://roselol.com/ rosD"
  - "rosD my new youtube video https://bit.ly/38iN6X2 rosD"
