# Broadcast Messages                                                                         

broadcasts:
  - "rosD https://roselol.com/ rosD"
  - "rosD https://roselol.com/guide/ rosD"
  - "rosD https://roselol.com/discord/ rosD"
  - "rosD https://roselol.com/twitter/ rosD"
  - "rosD https://roselol.com/instagram/ rosD"
